### ISSUE TITLE
Ad Campaigns - Setting Page not displayed correctly

### ISSUE THREAD

**Issue by rohit1290** [hypeJunction/Elgg-ads#1]
![capture](https://cloud.githubusercontent.com/assets/2772844/14050917/31d6205e-f2e5-11e5-9eb5-b75501a3fd5e.PNG)

Elgg: 1.12.8

**Comment by hypeJunction** [comment]
Download release packages or run composer install.

**Comment by rohit1290** [comment]
I have downloaded all the required plugins and activated it before activating ads plugin. Do i need to install any additional files?

I am testing it on my windows system using xampp.

**Comment by hypeJunction** [comment]
Don't use the Download zip. Go to releases tab and download from there
