### ISSUE TITLE
Fund getting added without going through paypal

### ISSUE THREAD

**Issue by rohit1290** [hypeJunction/Elgg-ads#2]
I have all the plugin installed for Ads.

When I click on "Add Fund" and try to add some money to the campaign, it's directly getting added without going through any paypal payment gateway. Am i missing something?

Img1
![1](https://cloud.githubusercontent.com/assets/2772844/14058715/c05423a2-f34f-11e5-9d1d-1d07ebdf0cda.PNG)

Img 2
![2](https://cloud.githubusercontent.com/assets/2772844/14058716/c533c404-f34f-11e5-9209-ba00bf8445dc.PNG)

**Comment by hypeJunction** [comment]
Login as non-admin. Admin just ads funda bypassing paywall.

**Comment by rohit1290** [comment]
Ok. 
Yes, its working for non-admins
